src/main/java/com/my/interrior/client/event/EventEntity.java
src/main/java/com/my/interrior/client/notice/NoticeEntity.java
src/main/java/com/my/interrior/client/pay/PayEntity.java
src/main/java/com/my/interrior/client/question/QuestionEntity.java

create table event, notice, pay, question table

create event, notice, pay, question table

---

.idea/vcs.xml
src/main/java/com/my/interrior/client/user/UserEntity.java
src/main/resources/templates/index.html

Chani  first 

---

src/main/java/com/my/interrior/client/user/UserController.java
src/main/resources/templates/client/login.html

login control

---

src/main/java/com/my/interrior/config/WebConfig.java
src/main/java/com/my/interrior/interceptor/Interceptor.java

인터셉터 작업 내용입니다.

---

src/main/java/com/my/interrior/client/mypage/MypageController.java
src/main/java/com/my/interrior/client/mypage/MypageDTO.java
src/main/java/com/my/interrior/client/mypage/MypageRepository.java
src/main/java/com/my/interrior/client/mypage/MypageRestController.java
src/main/java/com/my/interrior/client/mypage/MypageService.java
src/main/java/com/my/interrior/client/user/UserController.java
src/main/java/com/my/interrior/client/user/UserRepository.java
src/main/java/com/my/interrior/client/user/UserRestController.java
src/main/java/com/my/interrior/client/user/UserService.java
src/main/java/com/my/interrior/interceptor/Interceptor.java
src/main/resources/templates/client/mypage.html
src/main/resources/templates/index.html

User Update not Finish
회원정보 출력 완료
업데이트 기능 작업중,

User Update not Finish

---

build.gradle
src/main/java/com/my/interrior/client/user/UserController.java
src/main/java/com/my/interrior/client/user/UserRepository.java
src/main/java/com/my/interrior/client/user/UserService.java
src/main/java/com/my/interrior/config/WebSecurityConfig.java

비밀번호 암호화 완료

---

src/main/java/com/my/interrior/client/mypage/MypageController.java
src/main/java/com/my/interrior/client/mypage/MypageRepository.java
src/main/java/com/my/interrior/client/mypage/MypageRestController.java
src/main/java/com/my/interrior/client/mypage/MypageService.java
src/main/java/com/my/interrior/client/user/UserRestController.java
src/main/resources/templates/client/mypage.html

마이페이지 유저 정보 삭제 추가기능 구현

---

src/main/java/com/my/interrior/client/mypage/MypageRepository.java
src/main/java/com/my/interrior/client/user/UserController.java
src/main/java/com/my/interrior/client/user/UserRepository.java
src/main/java/com/my/interrior/client/user/UserRestController.java
src/main/resources/templates/client/findUId.html
src/main/resources/templates/client/login.html
src/main/resources/templates/index.html

사용자 아이디 찾기 초안

---

src/main/java/com/my/interrior/client/event/EventController.java
src/main/java/com/my/interrior/client/event/EventDTO.java
src/main/java/com/my/interrior/client/event/EventEntity.java
src/main/java/com/my/interrior/client/event/EventRepository.java
src/main/java/com/my/interrior/client/event/EventRestController.java
src/main/java/com/my/interrior/client/event/EventService.java
src/main/java/com/my/interrior/interceptor/Interceptor.java
src/main/resources/templates/client/event.html
src/main/resources/templates/client/eventDetail.html
src/main/resources/templates/index.html

이벤트 페이지 및 기능 구현 DAY-1
이벤트
이벤트 상세 페이지
이벤트 => DB에서 이벤트 리스트 조회해서 이벤트.html에 뿌려주기
이벤트 상세 페이지 =>이벤트 타이틀 누르면 상세 페이지 이동 (eventno)따서 맞게 뷰페이지에 뿌려주고

이벤트페이지 및 기능 구현 DAY-1

---

src/main/java/com/my/interrior/client/event/EventController.java
src/main/java/com/my/interrior/client/event/coupon/CouponEntity.java
src/main/java/com/my/interrior/client/event/coupon/CouponMapEntity.java
src/main/resources/templates/client/event.html
src/main/resources/templates/client/eventDetail.html
src/main/resources/templates/client/eventWrite.html
src/main/resources/templates/fragments/header.html

쿠폰 테이블 생성 및 쿠폰 매핑 테이플 생성, 비밀번호 변경 오류 수정

쿠폰 테이블 생성 및 쿠폰 매핑 테이플 생성, 비밀번호 변경 오류 수정

---

src/main/java/com/my/interrior/admin/coupon/CouponController.java
src/main/java/com/my/interrior/admin/coupon/CouponMapRepository.java
src/main/java/com/my/interrior/admin/coupon/CouponRepository.java
src/main/java/com/my/interrior/admin/coupon/CouponRestController.java
src/main/java/com/my/interrior/admin/coupon/CouponService.java
src/main/java/com/my/interrior/client/event/coupon/CouponEntity.java
src/main/java/com/my/interrior/client/event/coupon/CouponMapEntity.java
src/main/resources/templates/admin/coupon/couponWrite.html
src/main/resources/templates/client/eventDetail.html
src/main/resources/templates/client/mypage.html

이벤트 쿠폰 발급 로직
: 로그인이 되어있지 않은 상태에서 쿠폰 발급 못 함
로그인이 되어있는 상태에서 쿠폰 발급 가능
couponLimit을 기준으로 발급, couponLimit이 1일 때 한 번 발급받으면 다음에 또 발급 못 받음.
마이페이지에 내 쿠폰함 구현하고 view에 뿌릴 때 List<CouponEntity>로 가져옴.

이벤트 쿠폰 발급 및 마이페이지 내 쿠폰함 구현

---

src/main/java/com/my/interrior/client/shop/ShopController.java
src/main/java/com/my/interrior/client/shop/ShopOptionRepository.java
src/main/java/com/my/interrior/client/shop/ShopPhotoRepository.java
src/main/java/com/my/interrior/client/shop/ShopService.java
src/main/resources/templates/client/shop/shopList.html
src/main/resources/templates/fragments/header.html

shop 1차 수정

---

src/main/java/com/my/interrior/client/shop/ShopController.java
src/main/java/com/my/interrior/client/shop/ShopOptionRepository.java
src/main/java/com/my/interrior/client/shop/ShopOptionValueEntity.java
src/main/java/com/my/interrior/client/shop/ShopPhotoRepository.java
src/main/java/com/my/interrior/client/shop/ShopService.java
src/main/resources/static/css/shop.css
src/main/resources/templates/client/shop/shopDetail.html
src/main/resources/templates/client/shop/shopList.html
src/main/resources/templates/client/shop/shopWrite.html

Feature yjh

---

src/main/java/com/my/interrior/client/cart/CartController.java
src/main/java/com/my/interrior/client/cart/CartEntity.java
src/main/java/com/my/interrior/client/cart/CartOptionRepository.java
src/main/java/com/my/interrior/client/cart/CartOptionService.java
src/main/java/com/my/interrior/client/cart/CartRepository.java
src/main/java/com/my/interrior/client/cart/CartRestController.java
src/main/java/com/my/interrior/client/cart/CartService.java
src/main/java/com/my/interrior/client/shop/ShopController.java
src/main/java/com/my/interrior/client/shop/ShopOptionValueEntity.java
src/main/java/com/my/interrior/client/shop/ShopOptionValueRepository.java
src/main/java/com/my/interrior/client/shop/ShopOptionValueService.java
src/main/java/com/my/interrior/client/shop/ShopRepository.java
src/main/java/com/my/interrior/client/shop/ShopService.java
src/main/resources/templates/client/cart/cart.html
src/main/resources/templates/client/login.html
src/main/resources/templates/client/shop/shopDetail.html
src/main/resources/templates/client/shop/shopList.html
src/main/resources/templates/fragments/header.html

장바구니 구현, 삭제, 결제, 쿠폰 입력 아직 안 함

---

build.gradle
src/main/java/com/my/interrior/admin/coupon/CouponMapRepository.java
src/main/java/com/my/interrior/admin/coupon/CouponRepository.java
src/main/java/com/my/interrior/admin/coupon/CouponService.java
src/main/java/com/my/interrior/client/cart/CartController.java
src/main/java/com/my/interrior/client/pay/PaymentController.java
src/main/java/com/my/interrior/client/pay/PaymentService.java
src/main/java/com/my/interrior/client/pay/PrePaymentEntity.java
src/main/java/com/my/interrior/client/pay/PrePaymentRepository.java
src/main/java/com/my/interrior/client/user/UserRepository.java
src/main/java/com/my/interrior/client/user/UserService.java
src/main/resources/templates/client/cart/cart.html

장바구니에서 내가 가지고 있는 쿠폰 등록하는 것 완료
아직 안 한 거는 배송 테이블 만들기, 장바구니 삭제 기능, 결제 기능 구현하는 것.

장바구니 쿠폰 등록 구현

---

src/main/java/com/my/interrior/client/cart/CartController.java
src/main/java/com/my/interrior/client/pay/PayEntity.java
src/main/java/com/my/interrior/client/pay/PaymentAndShipmentDTO.java
src/main/java/com/my/interrior/client/pay/PaymentController.java
src/main/java/com/my/interrior/client/pay/PaymentRepository.java
src/main/java/com/my/interrior/client/pay/PaymentRestController.java
src/main/java/com/my/interrior/client/pay/PaymentService.java
src/main/java/com/my/interrior/client/pay/ShipmentEntity.java
src/main/java/com/my/interrior/client/pay/ShipmentRepository.java
src/main/java/com/my/interrior/client/pay/ShipmentService.java
src/main/resources/templates/client/cart/cart.html
src/main/resources/templates/client/pay/paymentInfo.html

일단 결제 시에 price 값은 10원으로 만들어 놓음
내일 돈 돌려주긴 하는데 그래도 우리 돈 소중히 !
결제를 완료했을 경우에 결제 완료 페이지로 넘어감.
내일은 장바구니에 있는 거 결제 시 삭제하고 쿠폰도 이미 쓴 쿠폰입니다. 만들고 몇 번 시도해보고 잘 된다 싶으면 결제 사전 검증이랑 price 다시 원래대로 되돌려 놓을 거임

결제 사전 검증 만들어 놓은 거 빼놓고 일단 계속 테스트 하는 중 주문 완료 하면 상품, 결제정보 나옴 70%정도 함

---

src/main/java/com/my/interrior/admin/coupon/CouponController.java
src/main/java/com/my/interrior/admin/coupon/CouponMapRepository.java
src/main/java/com/my/interrior/admin/coupon/CouponRestController.java
src/main/java/com/my/interrior/admin/coupon/CouponService.java
src/main/java/com/my/interrior/client/cart/CartController.java
src/main/java/com/my/interrior/client/cart/CartEntity.java
src/main/java/com/my/interrior/client/cart/CartOptionRepository.java
src/main/java/com/my/interrior/client/cart/CartRepository.java
src/main/java/com/my/interrior/client/cart/CartRestController.java
src/main/java/com/my/interrior/client/cart/CartService.java
src/main/java/com/my/interrior/client/event/coupon/CouponEntity.java
src/main/java/com/my/interrior/client/event/coupon/CouponMapEntity.java
src/main/java/com/my/interrior/client/pay/PaymentController.java
src/main/resources/templates/client/cart/cart.html
src/main/resources/templates/client/mypage/mypage.html

쿠폰의 used_date를 사용함
null값이면 값을 가져오고 used_date의 날짜가 있다면 쿠폰을 쓴 것으로 침.
아직 결제 시 장바구니 삭제는 작업 안 함
그리고 used_date를 통해서 나중에 환불처리할 때 다시 null로 되돌려 놓을 예정
환불은 결제 날로부터 하루 이내에 100% 환불, 이틀 이내에 50% 환불 3일 이상은 환불 x
제품에 하자가 있는 경우는 나중에 생각해봄.

결제 완료 시 쿠폰 적용한 거 사라지고 내 쿠폰함에서도 사라짐

---

src/main/java/com/my/interrior/client/cart/CartOptionRepository.java
src/main/java/com/my/interrior/client/cart/CartRepository.java
src/main/java/com/my/interrior/client/cart/CartRestController.java
src/main/resources/templates/client/cart/cart.html

Feature hmw

---

src/main/java/com/my/interrior/client/cart/CartOptionEntity.java
src/main/java/com/my/interrior/client/pay/PaymentRestController.java

윤재환이 이상하게 만든 거 고침(co_no, paid_at)

윤재환이 이상하게 만든 거 고침(co_no, paid_at)

---

src/main/java/com/my/interrior/client/cart/CartController.java
src/main/java/com/my/interrior/client/ordered/OrderedController.java
src/main/java/com/my/interrior/client/ordered/OrderedDTO.java
src/main/java/com/my/interrior/client/ordered/OrderedEntity.java
src/main/java/com/my/interrior/client/ordered/OrderedRepository.java
src/main/java/com/my/interrior/client/ordered/OrderedRestController.java
src/main/java/com/my/interrior/client/ordered/OrderedService.java
src/main/java/com/my/interrior/client/pay/PaymentAndUserEntity.java
src/main/java/com/my/interrior/client/pay/PaymentAndUserRepository.java
src/main/java/com/my/interrior/client/pay/PaymentRestController.java
src/main/java/com/my/interrior/client/shop/ShopRepository.java
src/main/java/com/my/interrior/client/shop/ShopService.java
src/main/resources/templates/client/cart/cart.html
src/main/resources/templates/client/mypage/mypage.html

주문 내역 1차 구현 완료 환불처리, 가격 상세, 배송 상태 미 포함
내일이나 오늘 저녁에 잡을 듯? 가격이랑 배송 상태 잡고 환불 처리 들어가봄
환불 처리는  당일 날만 가능하게끔 할 예정

주문 내역 1차 구현 완료 환불처리, 가격 상세, 배송 상태 미 포함

---

src/main/java/com/my/interrior/client/ordered/OrderedEntity.java
src/main/java/com/my/interrior/client/ordered/OrderedRepository.java
src/main/java/com/my/interrior/client/ordered/OrderedRestController.java
src/main/java/com/my/interrior/client/ordered/OrderedService.java
src/main/java/com/my/interrior/client/pay/IamportTokenResponse.java
src/main/java/com/my/interrior/client/pay/PaymentAndUserRepository.java
src/main/java/com/my/interrior/client/pay/PaymentAndUserService.java
src/main/java/com/my/interrior/client/pay/PaymentRepository.java
src/main/java/com/my/interrior/client/pay/PaymentRestController.java
src/main/java/com/my/interrior/client/pay/PaymentService.java
src/main/java/com/my/interrior/config/WebConfig.java
src/main/resources/templates/client/cart/cart.html
src/main/resources/templates/client/mypage/mypage.html

결제 시 장바구니 삭제, 쿠폰 입력 된 거 삭제, 환불 처리 확인, 스크립트 공격으로 사전 결제 검증 확인

환불 완료, 사전 결제 검증 완료, 결제 완료

---

src/main/java/com/my/interrior/three/DataEntity.java
src/main/java/com/my/interrior/three/PointEntity.java
src/main/java/com/my/interrior/three/ThreeEntity.java

3d 인테리어 저장하는 데 필요한 속성들 일단 집어넣음.

3D 테이블 3개 만듦 three, data, point

---

src/main/java/com/my/interrior/IDesignApplication.java
src/main/java/com/my/interrior/client/ordered/OrderedService.java

주문 내역에 배송쪽 로직 만듦
결제가 오늘이면 일단 배송 준비중, 어제면 배송 중, 이틀 전부터는 쭉 배송 완료 처리

주문 내역에 배송쪽 로직 만듦

---

src/main/java/com/my/interrior/client/evaluation/ReviewCommentEntity.java
src/main/java/com/my/interrior/config/WebConfig.java
src/main/java/com/my/interrior/tempCodeRunnerFile.java
src/main/java/com/my/interrior/three/DataEntity.java
src/main/java/com/my/interrior/three/SaveProjectRequest.java
src/main/java/com/my/interrior/three/ThreeService.java
src/main/resources/dimension/dashboard/src/dashboard.js
src/main/resources/templates/admin/page/adminFAQ.html
src/main/resources/templates/admin/page/adminReview.html
src/main/resources/templates/client/mypage/mypageUpdatePassword.html
src/main/resources/templates/client/review/reviewList.html

대시보드 api 저장하기 구현

---

src/main/java/com/my/interrior/three/SaveProjectRequest.java
src/main/java/com/my/interrior/three/ThreeEntity.java
src/main/java/com/my/interrior/three/ThreeRestController.java
src/main/java/com/my/interrior/three/ThreeService.java
src/main/resources/dimension/dashboard/dashboard.html
src/main/resources/dimension/three/src/three.js

thumbnail에 GCS 필요
위치는 threeService.java
MultipartFile에 thumbnail 객체로 담아놓음

thumbnail에 GCS 필요

---

src/main/java/com/my/interrior/three/SaveProjectRequest.java
src/main/java/com/my/interrior/three/ThreeRestController.java
src/main/java/com/my/interrior/three/ThreeService.java

3D gcs 이미지, JSON 객체 테이블 데이터 추가 완료

3D gcs 이미지, JSON 객체 테이블 데이터 추가 완료

---

src/main/java/com/my/interrior/three/GetProjectsRequest.java
src/main/java/com/my/interrior/three/GetProjectsResponse.java
src/main/java/com/my/interrior/three/ThreeRepository.java
src/main/java/com/my/interrior/three/ThreeRestController.java
src/main/java/com/my/interrior/three/ThreeService.java
src/main/resources/dimension/dashboard/src/dashboard.js

3D 불러오기 작업 중

---

build.gradle
src/main/java/com/my/interrior/three/ThreeRepository.java
src/main/java/com/my/interrior/three/ThreeRestController.java
src/main/java/com/my/interrior/three/ThreeService.java
src/main/resources/dimension/dashboard/src/dashboard.js

3D dashboard 불러오기 구현 중 거의 완료

---

src/main/java/com/my/interrior/config/WebConfig.java
src/main/java/com/my/interrior/three/ThreeRepository.java
src/main/java/com/my/interrior/three/ThreeService.java

3D dashboard response 확인완료
response 받고 확인 바람.

3D dashboard response 확인완료

---

.gitignore

개발, 배포 분리작업

---

src/main/resources/application.properties

배포, 개발 모드 분리
application-dev.properties
application-prod.properties 추가

배포, 개발 모드 분리

---

package-lock.json
src/main/java/com/my/interrior/three/GetProjectsResponse.java
src/main/java/com/my/interrior/three/ThreeRestController.java
src/main/resources/application.properties

대시보드 getProjects 수정
projectId 추가

대시보드 getProjects 수정

---

Dockerfile
src/main/resources/application.properties
src/main/resources/dimension/src/dashboard.js

Dockerfile, application.properties 수정
ENV 추가,  application.properties에서 배포 모드 삭제

Dockerfile, application.properties 수정

---

src/main/resources/templates/admin/chat.html
src/main/resources/templates/index.html

chat ws 설정
index.html에서
//서버의 broadsocket의 서블릿으로 웹 소켓 시작
var webSocket = new WebSocket(`ws://${window.location.host}/broadsocket`); 로 변경
chat.html에서
//서버의 admin의 서블릿으로 웹 소켓을 한다.
var webSocket = new WebSocket(`ws://${window.location.host}/adminBroadsocket`);
이걸로 변경

chat ws 설정

---

src/main/java/com/my/interrior/client/user/UserController.java
src/main/java/com/my/interrior/client/user/UserMailDTO.java
src/main/java/com/my/interrior/client/user/UserRestController.java
src/main/java/com/my/interrior/client/user/UserService.java
src/main/resources/templates/client/findUId.html
src/main/resources/templates/client/findUPw.html

findId, findPw.html js 수정
findId
Bad Request일 때 리턴,
Not Found일 때 리턴,
Post에서 Get으로 변경,
JSON에서 쿼리 스트링으로 받게 변경(@RequestBody -> @RequestParam)
findPw
Bad Request일 때 리턴,
Not found일 때 리턴,
컨트롤러에서 UName 삭제.

findId, findPw.html js 수정

---

src/main/java/com/my/interrior/client/cart/CartRestController.java
src/main/java/com/my/interrior/client/cart/CartService.java
src/main/java/com/my/interrior/three/CreateProjectRequest.java
src/main/java/com/my/interrior/three/DataRepository.java
src/main/java/com/my/interrior/three/PointRepository.java
src/main/java/com/my/interrior/three/SaveProjectRequest.java
src/main/java/com/my/interrior/three/ThreeController.java
src/main/java/com/my/interrior/three/ThreeRepository.java
src/main/java/com/my/interrior/three/ThreeRestController.java
src/main/java/com/my/interrior/three/ThreeService.java
src/main/resources/dimension/src/dashboard.js
src/main/resources/dimension/src/three.js

대시보드 불러오기 api, 삭제 api 구현 중

---

src/main/resources/webpack.config.js

여전히 삭제 api 구현중

---

src/main/java/com/my/interrior/three/DataRepository.java
src/main/java/com/my/interrior/three/PointRepository.java
src/main/java/com/my/interrior/three/ThreeRepository.java
src/main/java/com/my/interrior/three/ThreeRestController.java
src/main/java/com/my/interrior/three/ThreeService.java

대시보드 삭제 api 구현 완료

---

src/main/java/com/my/interrior/config/SingleOrListDeserializer.java
src/main/java/com/my/interrior/config/WebConfig.java
src/main/java/com/my/interrior/three/SaveProjectRequest.java
src/main/resources/lib/three/loader/furnitures.js

대시보드 배열, 객체 확인
SingleOrListDeserializer.java --> config에서 확인
point가 room에서는 리스트형태로 받아오는데 room 안에 있는 chair나 다른 것들이 단일 객체로 받아와져서 만듦.

대시보드 배열, 객체 확인

---

src/main/resources/static/css/mypage/mypage.css
src/main/resources/static/js/mypage/mypage.js
src/main/resources/templates/client/mypage/mypage.html

마이페이지 QA 확인

---

build.gradle
src/main/java/com/my/interrior/client/mypage/MypageRestController.java
src/main/java/com/my/interrior/client/user/UserController.java
src/main/java/com/my/interrior/client/user/UserRestController.java
src/main/java/com/my/interrior/common/CommonResponse.java
src/main/java/com/my/interrior/common/DefaultApiResponse.java
src/main/java/com/my/interrior/common/Result.java
src/main/java/com/my/interrior/config/WebConfig.java
src/main/java/com/my/interrior/error/GlobalExceptionHandler.java
src/main/resources/static/js/findUId.js
src/main/resources/static/js/findUPw.js
src/main/resources/static/js/join.js
src/main/resources/static/js/mypage/mypage.js
src/main/resources/static/js/shop/shopWrite.js
src/main/resources/templates/client/eventWrite.html
src/main/resources/templates/client/join.html

Swagger 수정 중

---

src/main/java/com/my/interrior/admin/coupon/CouponRestController.java
src/main/java/com/my/interrior/client/cart/CartRestController.java
src/main/java/com/my/interrior/client/ordered/OrderedRestController.java
src/main/java/com/my/interrior/client/pay/PaymentRestController.java
src/main/java/com/my/interrior/three/ThreeRestController.java
src/main/resources/application.properties

내 쪽 API 명세서 작성

---

src/main/java/com/my/interrior/config/WebConfig.java

CORS 에러 해결

---

src/main/java/com/my/interrior/config/WebConfig.java

config 프린터 제거 이거 뭐냐 재환아 ㅡㅡ

---

src/main/resources/static/js/a.js
src/main/resources/templates/client/shop/shopDetail.html

장바구니 담기 수정

---

src/main/resources/static/js/cart/cart.js

장바구니 삭제 수정

---

src/main/resources/static/js/cart/cart.js

cart.js QA

---

nginx.conf
nginx/nginx.blue.conf
nginx/nginx.green.conf

Websocket QA

---

src/main/resources/templates/fragments/footer.html
src/main/resources/templates/fragments/header.html

인덱스 수정 final

---

src/main/resources/application.properties

인덱스, application.properties 수정

인덱스, application.properties 수정

---

src/main/resources/application.properties

application.properties dialect 수정

application.properties dialect 수정

---

docker-compose.yml
dockercompose/docker-compose.green.yml

해킹 막기 비번 변경
prod, private, docker-compose, compose.green, compose.blue.conf 변경

해킹 막기 비번 변경

---

.github/workflows/deploy.yaml

security fixed
